# Generated by Django 4.0.5 on 2022-06-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leotapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
