# Generated by Django 4.0.5 on 2022-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leotapp', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
