# Generated by Django 4.0.5 on 2022-06-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leotapp', '0004_alter_register_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='courses',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
